INSERT INTO `tblemailtemplates` (`type`, `slug`, `language`, `name`, `subject`, `message`, `fromname`, `fromemail`, `plaintext`, `active`, `order`) VALUES
('contract', 'contract-signed-to-customer', 'english', 'Contract Signed (Sent to Customer)', 'Thank you for signing Contract', '<p>Dear <span style="font-size: 12pt;">{contact_firstname}&nbsp;{contact_lastname}</span><br /><br />Thank for for signing the contract.</p>
<p><span style="font-size: 12pt;">Please find the <a href="{contract_link}">{contract_subject}</a> attached.</span><br /><br />We look forward to doing business with you.<br /><br />We will contact you as soon as possible<br /><br />Kind Regards,<br />{email_signature}</p>', '{companyname} | CRM', '', 0, 1, 0),
('contract', 'contract-signed-to-customer', 'bulgarian', 'Contract Signed (Sent to Customer) [bulgarian]', 'Thank you for signing Contract', '', '{companyname} | CRM', NULL, 0, 1, 0),
('contract', 'contract-signed-to-customer', 'catalan', 'Contract Signed (Sent to Customer) [catalan]', 'Thank you for signing Contract', '', '{companyname} | CRM', NULL, 0, 1, 0),
('contract', 'contract-signed-to-customer', 'chinese', 'Contract Signed (Sent to Customer) [chinese]', 'Thank you for signing Contract', '', '{companyname} | CRM', NULL, 0, 1, 0),
('contract', 'contract-signed-to-customer', 'czech', 'Contract Signed (Sent to Customer) [czech]', 'Thank you for signing Contract', '', '{companyname} | CRM', NULL, 0, 1, 0),
('contract', 'contract-signed-to-customer', 'dutch', 'Contract Signed (Sent to Customer) [dutch]', 'Thank you for signing Contract', '', '{companyname} | CRM', NULL, 0, 1, 0),
('contract', 'contract-signed-to-customer', 'french', 'Contract Signed (Sent to Customer) [french]', 'Thank you for signing Contract', '', '{companyname} | CRM', NULL, 0, 1, 0),
('contract', 'contract-signed-to-customer', 'german', 'Contract Signed (Sent to Customer) [german]', 'Thank you for signing Contract', '', '{companyname} | CRM', NULL, 0, 1, 0),
('contract', 'contract-signed-to-customer', 'greek', 'Contract Signed (Sent to Customer) [greek]', 'Thank you for signing Contract', '', '{companyname} | CRM', NULL, 0, 1, 0),
('contract', 'contract-signed-to-customer', 'indonesia', 'Contract Signed (Sent to Customer) [indonesia]', 'Thank you for signing Contract', '', '{companyname} | CRM', NULL, 0, 1, 0),
('contract', 'contract-signed-to-customer', 'italian', 'Contract Signed (Sent to Customer) [italian]', 'Thank you for signing Contract', '', '{companyname} | CRM', NULL, 0, 1, 0),
('contract', 'contract-signed-to-customer', 'japanese', 'Contract Signed (Sent to Customer) [japanese]', 'Thank you for signing Contract', '', '{companyname} | CRM', NULL, 0, 1, 0),
('contract', 'contract-signed-to-customer', 'persian', 'Contract Signed (Sent to Customer) [persian]', 'Thank you for signing Contract', '', '{companyname} | CRM', NULL, 0, 1, 0),
('contract', 'contract-signed-to-customer', 'polish', 'Contract Signed (Sent to Customer) [polish]', 'Thank you for signing Contract', '', '{companyname} | CRM', NULL, 0, 1, 0),
('contract', 'contract-signed-to-customer', 'portuguese', 'Contract Signed (Sent to Customer) [portuguese]', 'Thank you for signing Contract', '', '{companyname} | CRM', NULL, 0, 1, 0),
('contract', 'contract-signed-to-customer', 'portuguese_br', 'Contract Signed (Sent to Customer) [portuguese_br]', 'Thank you for signing Contract', '', '{companyname} | CRM', NULL, 0, 1, 0),
('contract', 'contract-signed-to-customer', 'romanian', 'Contract Signed (Sent to Customer) [romanian]', 'Thank you for signing Contract', '', '{companyname} | CRM', NULL, 0, 1, 0),
('contract', 'contract-signed-to-customer', 'russian', 'Contract Signed (Sent to Customer) [russian]', 'Thank you for signing Contract', '', '{companyname} | CRM', NULL, 0, 1, 0),
('contract', 'contract-signed-to-customer', 'slovak', 'Contract Signed (Sent to Customer) [slovak]', 'Thank you for signing Contract', '', '{companyname} | CRM', NULL, 0, 1, 0),
('contract', 'contract-signed-to-customer', 'spanish', 'Contract Signed (Sent to Customer) [spanish]', 'Thank you for signing Contract', '', '{companyname} | CRM', NULL, 0, 1, 0),
('contract', 'contract-signed-to-customer', 'swedish', 'Contract Signed (Sent to Customer) [swedish]', 'Thank you for signing Contract', '', '{companyname} | CRM', NULL, 0, 1, 0),
('contract', 'contract-signed-to-customer', 'turkish', 'Contract Signed (Sent to Customer) [turkish]', 'Thank you for signing Contract', '', '{companyname} | CRM', NULL, 0, 1, 0),
('contract', 'contract-signed-to-customer', 'ukrainian', 'Contract Signed (Sent to Customer) [ukrainian]', 'Thank you for signing Contract', '', '{companyname} | CRM', NULL, 0, 1, 0),
('contract', 'contract-signed-to-customer', 'vietnamese', 'Contract Signed (Sent to Customer) [vietnamese]', 'Thank you for signing Contract', '', '{companyname} | CRM', NULL, 0, 1, 0);